I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 60, in script
    show her with dissolve1
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 60, in script
    show her with dissolve1
  File "F:\renpy-8.3.2-sdk\renpy\ast.py", line 1361, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "F:\renpy-8.3.2-sdk\renpy\exports\statementexports.py", line 257, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "F:\renpy-8.3.2-sdk\renpy\display\core.py", line 1578, in do_with
    return self.interact(trans_pause=True,
  File "F:\renpy-8.3.2-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "F:\renpy-8.3.2-sdk\renpy\display\core.py", line 2666, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "F:\renpy-8.3.2-sdk\renpy\display\core.py", line 2575, in instantiate_transition
    trans = self.ongoing_transition[layer](
TypeError: 'Dissolve' object is not callable

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.2.24090902
5 Days 2
Sun May 11 22:28:44 2025
