I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script4.rpy", line 114, in script
    if bath2:
  File "game/script4.rpy", line 114, in <module>
    if bath2:
NameError: name 'bath2' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script4.rpy", line 114, in script
    if bath2:
  File "C:\Users\memor.DESKTOP-AEKJ83H\Downloads\renpy-8.3.7-sdk\renpy-8.3.7-sdk\renpy\ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\memor.DESKTOP-AEKJ83H\Downloads\renpy-8.3.7-sdk\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\memor.DESKTOP-AEKJ83H\Downloads\renpy-8.3.7-sdk\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script4.rpy", line 114, in <module>
    if bath2:
NameError: name 'bath2' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
5 Days 2
Tue May 13 18:27:48 2025
